app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


$proxy_url    = env('PROXY_URL');
$proxy_schema = env('PROXY_SCHEMA');

if (!empty($proxy_url)) {
	URL::forceRootUrl($proxy_url);
}

if (!empty($proxy_schema)) {
	URL::forceSchema($proxy_schema);
}


include __DIR__ . '/Routes/api.php';
include __DIR__ . '/Routes/autocomplete.php';
include __DIR__ . '/Routes/developer_zone.php';

Route::get('/', function () {
	return response()->redirectToRoute('login');
});

Route::get('login', function () {
	return response()->redirectToRoute('login');
});

Route::get('logout', function () {
	return response()->redirectToRoute('logout');
});

Route::group(['middleware' => ['auth', 'role:usuario'], 'prefix' => 'actas/'], function () {
	require(__DIR__ . '/Routes/actas.php');
});

Route::group(['middleware' => 'auth', 'prefix' => 'centros/'], function () {
	require(__DIR__ . '/Routes/centros.php');
});

Route::group(['middleware' => 'auth', 'prefix' => 'comisiones/'], function () {
	require(__DIR__ . '/Routes/comisiones.php');
});

Route::group(['middleware' => 'auth', 'prefix' => 'plantillas/'], function () {
	require(__DIR__ . '/Routes/plantillas.php');
});

Route::group(['prefix' => 'auth/'], function () {
	require(__DIR__ . '/Routes/auth.php');
});

Route::group(['prefix' => 'password/'], function () {
	require(__DIR__ . '/Routes/passwords.php');
});

Route::group(['middleware' => ['auth'], 'prefix' => 'reportes/'], function () {
	require(__DIR__ . '/Routes/reportes.php');
});

Route::group(['middleware' => ['auth', 'role:usuario', 'processIsOpen'], 'prefix' => 'reportes/'], function () {
	require(__DIR__ . '/Routes/actualizaciones.php');
	require(__DIR__ . '/Routes/actualizacion_centros.php');
	require(__DIR__ . '/Routes/actualizacion_comisiones.php');
	require(__DIR__ . '/Routes/actualizacion_presidentes.php');
	require(__DIR__ . '/Routes/actualizacion_secretarios.php');
	require(__DIR__ . '/Routes/actualizacion_vocales.php');
});

Route::group(['middleware' => ['auth'], 'prefix' => 'verificaciones/'], function () {
	require(__DIR__ . '/Routes/verificaciones.php');
});

Route::group(['middleware' => ['auth'], 'prefix' => 'incidencias/'], function () {
	require(__DIR__ . '/Routes/verificacionIncidencias.php');
});

Route::group(['middleware' => ['auth'], 'prefix' => 'calendarios/'], function () {
	require(__DIR__ . '/Routes/calendarios.php');
	require(__DIR__ . '/Routes/calendario_actividad.php');
});

Route::group(['middleware' => ['auth', 'role:operador'], 'prefix' => 'admin/'], function () {
	require(__DIR__ . '/Routes/admin.php');
});

include __DIR__ . '/Routes/cat_incidencias.php';

Route::group(['prefix' => 'admin/catalogos/configuracion'], function () {
	require(__DIR__ . '/Routes/cat_configuracion_sistema.php');
});

Route::group(['prefix' => 'admin/catalogos/sindicatos'], function () {
	require(__DIR__ . '/Routes/cat_sindicatos.php');
});

Route::group(['prefix' => 'admin/consulta/claveComision'], function () {
	require(__DIR__ . '/Routes/consulta_claveComision.php');
});
Route::group(['middleware' => ['auth'], 'prefix' => 'centro/'], function () {
	require(__DIR__ . '/Routes/centros.php');
});

Route::group(['middleware' => ['auth', 'role:usuario'], 'prefix' => 'comision/'], function () {
	require(__DIR__ . '/Routes/comision.php');
	require(__DIR__ . '/Routes/comision_centros.php');
	require(__DIR__ . '/Routes/comision_vocales.php');
	require(__DIR__ . '/Routes/comision_presidentes.php');
	require(__DIR__ . '/Routes/comision_secretarios.php');
});

Route::group(['middleware' => ['auth', 'role:operador'], 'prefix' => 'usuarios'], function () {
	require(__DIR__ . '/Routes/users.php');
	require(__DIR__ . '/Routes/password.php');
});

Route::group(['middleware' => ['auth'], 'prefix' => 'configuracion'], function () {
	require(__DIR__ . '/Routes/etapa_proceso.php');
});

Route::get('libre/', ['as'=>'libre', function () {
	dd('libre');
}]);

Route::get('acceso-denegado', ['as'=>'invitado', 'middleware'=>['auth'], function(){
	return view('plantillas.invitado');
}]);

app/Models/User.php
<?php

namespace SeguridadHigiene\Models;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['role', 'email', 'password', 'username'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];

	public function comision()
	{
		return $this->hasOne(Comision::class);
	}

	public function getNombreCompletoAttribute()
	{
		return $this->primer_apellido." ".$this->segundo_apellido." ".$this->name;
	}

	public function data()
	{
		return $this->hasOne(UserData::class);
	}

	public function hasRole($role)
	{
		return $this->role == $role ? true : false;
	}

}

resources/views/admin/partials/actualizacion.blade.php
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-success">
            <div class="panel-heading">
                Datos de la actualización
                <span class="glyphicon glyphicon-menu-up pull-right" id="panel-comision"></span>
            </div>
            <div class="panel-body">
                <div id="content">
                    <ul id="tabs_comision" class="nav nav-tabs" data-tabs="tabs">
                        <li class="active"><a href="#centro_trabajo_actualizacion" data-toggle="tab">Centro de trabajo</a>
                        </li>
                        <li><a href="#presidente_actualizacion" data-toggle="tab">Presidente</a></li>
                        <li><a href="#secretario_actualizacion" data-toggle="tab">Secretario</a></li>
                        <li><a href="#vocales_actualizacion" data-toggle="tab">Vocales</a></li>
                        <li><a href="#documentacion_actualizacion" data-toggle="tab">Documentación anexa</a></li>
                    </ul>
                    <div id="tabs_verificacion_content" class="tab-content">
                        <div class="tab-pane active" id="centro_trabajo_actualizacion">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>
                                            Clave CT
                                        </th>
                                        <th>
                                            Nombre
                                        </th>
                                        <th>
                                            Turno
                                        </th>
                                        <th>
                                            Municipio
                                        </th>
                                        <th>
                                            Localidad
                                        </th>
                                        <th>
                                            Nivel
                                        </th>
                                        <th>
                                            Modalidad
                                        </th>
                                        <th>Acción</th>
                                    </tr>
                                    </thead>
                                    <tbody id="myTable">
                                    @if(!$reporte->actualizacion->centroTransacciones)
                                        <tr>
                                            <td colspan="8"> <p>Sin actualizacion de centros de trabajo</p> </td>
                                        </tr>
                                        @else
                                        @foreach ($reporte->actualizacion->centroTransacciones as $centro)
                                            <tr class="{{ $centro->actions == "Delete" ? "danger":"success" }}">
                                                <td>{{$centro->escuela_lite->cct}}</td>
                                                <td>{{$centro->escuela_lite->nombre}}</td>
                                                <td>{{$centro->escuela_lite->turno->d_turno}}</td>
                                                <td>{{$centro->escuela_lite->d_municipio}}</td>
                                                <td>{{$centro->escuela_lite->d_localidad}}</td>
                                                <td>{{$centro->escuela_lite->nivel}}</td>
                                                <td>{{$centro->escuela_lite->modalidad}}</td>
                                                <td>@if ($centro->actions == 'Delete')
                                                        Eliminar
                                                    @elseif ($centro->actions == 'Insert')
                                                        Agregar
                                                    @endif
                                                </td>
                                            </tr>
                                        @endforeach
                                        @endif
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="tab-pane" id="presidente_actualizacion">
                            <br>
                                <div class="row">
                                    <div class="col-sm-6 form-group">
                                        {!! Form::label ('presidente', 'Nombre:') !!}
                                        {!! Form::text('presidente', isset($reporte->actualizacion->presidenteTransacciones->nombre_completo) ? $reporte->actualizacion->presidenteTransacciones->nombre_completo : null , array('class' => 'form-control', 'readonly' => true)) !!}
                                    </div>
                                    <div class="col-sm-6 form-group">
                                        {!! Form::label ('cargo', 'Cargo:') !!}
                                        {!! Form::text('cargo', isset($reporte->actualizacion->presidenteTransacciones->cargo) ? $reporte->actualizacion->presidenteTransacciones->cargo : null, array('class' => 'form-control', 'readonly' => true)) !!}
                                    </div>
                                </div>
                        </div>
                        <div class="tab-pane" id="secretario_actualizacion">
                            <br>
                                <div class="row">
                                    <div class="col-sm-6 form-group">
                                        {!! Form::label ('secretario', 'Nombre:') !!}
                                        {!! Form::text('secretario', isset($reporte->actualizacion->secretarioTransacciones->nombre_completo) ? $reporte->actualizacion->secretarioTransacciones->nombre_completo : null, array('class' => 'form-control', 'readonly' => true)) !!}
                                    </div>
                                    <div class="col-sm-3 form-group">
                                        <?php
                                            if (!isset($reporte->actualizacion->secretarioTransacciones->sector))
                                                $sector = null;
                                            else
                                                if ($reporte->actualizacion->secretarioTransacciones->sector == 1)
                                                    $sector = 'OFICIAL';
                                                else if ($reporte->actualizacion->secretarioTransacciones->sector = 2)
                                                    $sector = 'SINDICAL';
                                        ?>
                                        {!! Form::label ('sector', 'Sector:') !!}
                                        {!! Form::text('sector', $sector , array('class' => 'form-control', 'readonly' => true)) !!}
                                    </div>
                                    <div class="col-sm-3 form-group">
                                        {!! Form::label ('rfc', 'RFC:') !!}
                                        {!! Form::text('rfc', isset($reporte->actualizacion->secretarioTransacciones->rfc) ? $reporte->actualizacion->secretarioTransacciones->rfc : null, array('class' => 'form-control', 'readonly' => true)) !!}
                                    </div>
                                </div>
                        </div>
                        <div class="tab-pane" id="vocales_actualizacion">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>
                                        Nombre
                                    </th>
                                    <th>
                                        Cargo
                                    </th>
                                    <th>
                                        Sector
                                    </th>
                                    <th>
                                        Tipo de representación
                                    </th>
                                </tr>
                                </thead>
                                <tbody id="myTable">
                                @if(!$reporte->actualizacion->vocalTransacciones)
                                    <tr>
                                        <td colspan="8"> <p>Sin actualización de vocales</p> </td>
                                    </tr>
                                    @else
                            @foreach($reporte->actualizacion->vocalTransacciones as $vocal)
                                <tr class="{{ $centro->actions == "Delete" ? "danger":"success" }}">
                                    <td>{{$vocal->nombre_completo}}</td>
                                    <td>{{$vocal->cargo}}</td>
                                    <td>{{$vocal->nombreSector}}</td>
                                    <td>{{$vocal->nombreTipo}}</td>
                                    <td>@if ($vocal->actions == 'Delete')
                                            Eliminar
                                        @elseif ($vocal->actions == 'Insert')
                                            Agregar
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                                    @endif
                                </tbody>
                            </table>
                        </div>
                        <div class="tab-pane" id="documentacion_actualizacion">
                            <br>
                                <div class="row">
                                    <div class="col-sm-3 control-label" style="text-align: left!important">
                                        {!! Form::label ('oficio_oficial', 'Oficio designación oficial:') !!}
                                    </div>
                                    <div class="col-sm-3">
                                        {!! Form::text('oficio_oficial', isset($reporte->actualizacion->num_oficio_oficial) ? $reporte->actualizacion->num_oficio_oficial : null, array('class' => 'form-control', 'readonly' => true)) !!}
                                    </div>
                                    <div class="col-sm-3 control-label" style="text-align: left!important">
                                        {!! Form::label ('fecha_oficio_oficial', 'Fecha:') !!}
                                    </div>
                                    <div class="col-sm-3">
                                        {!! Form::text('fecha_oficio_oficial', isset($reporte->actualizacion->fecha_oficio_oficial) ? $reporte->actualizacion->fecha_oficio_oficial : null, array('class' => 'form-control', 'readonly' => true)) !!}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-3 control-label" style="text-align: left!important">
                                        {!! Form::label ('oficio_sindical', 'Oficio designación sindical:') !!}
                                    </div>
                                    <div class="col-sm-3">
                                        {!! Form::text('oficio_sindical', isset($reporte->actualizacion->num_oficio_sindical) ? $reporte->actualizacion->num_oficio_sindical : null, array('class' => 'form-control', 'readonly' => true)) !!}
                                    </div>
                                    <div class="col-sm-3 control-label" style="text-align: left!important">
                                        {!! Form::label ('fecha_oficio_sindical', 'Fecha:') !!}
                                    </div>
                                    <div class="col-sm-3">
                                        {!! Form::text('fecha_oficio_sindical', isset($reporte->actualizacion->fecha_oficio_sindical) ? $reporte->actualizacion->fecha_oficio_sindical : null, array('class' => 'form-control', 'readonly' => true)) !!}
                                    </div>
                                </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/admin/partials/comision.blade.php
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-success">
            <div class="panel-heading">
                Datos de la comisión
                <span class="glyphicon glyphicon-menu-up pull-right" id="panel-comision"></span>
            </div>
            <div class="panel-body">
                <div id="content">
                    <ul id="tabs_comision" class="nav nav-tabs" data-tabs="tabs">
                        <li class="active"><a href="#centro_trabajo" data-toggle="tab">Centro de trabajo</a>
                        </li>
                        <li><a href="#sindicato" data-toggle="tab">Organización sindical</a></li>
                        <li><a href="#presidente" data-toggle="tab">Presidente</a></li>
                        <li><a href="#secretario" data-toggle="tab">Secretario</a></li>
                        <li><a href="#vocales" data-toggle="tab">Vocales</a></li>
                        <li><a href="#documentacion" data-toggle="tab">Documentación anexa</a></li>
                    </ul>
                    <div id="tabs_verificacion_content" class="tab-content">
                        <div class="tab-pane active" id="centro_trabajo">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>
                                            Clave CT
                                        </th>
                                        <th>
                                            Nombre
                                        </th>
                                        <th>
                                            Turno
                                        </th>
                                        <th>
                                            Municipio
                                        </th>
                                        <th>
                                            Localidad
                                        </th>
                                        <th>
                                            Nivel
                                        </th>
                                        <th>
                                            Modalidad
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody id="myTable">
                                    @forelse($reporte->comision->centros as $centro)
                                        <tr>
                                            <td>{{$centro->escuela_lite->cct}}</td>
                                            <td>{{$centro->escuela_lite->nombre}}</td>
                                            <td>{{$centro->escuela_lite->turno->d_turno}}</td>
                                            <td>{{$centro->escuela_lite->d_municipio}}</td>
                                            <td>{{$centro->escuela_lite->d_localidad}}</td>
                                            <td>{{$centro->escuela_lite->nivel}}</td>
                                            <td>{{$centro->escuela_lite->modalidad}}</td>
                                        </tr>
                                    @empty
                                        <tr>
                                            <td colspan="7"> <p>No contiene centros de trabajo</p> </td>
                                        </tr>
                                    @endforelse
                                   </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="tab-pane" id="sindicato">
                            <br>
                            <div class="form-group">
                                 {!! Form::label ('sindicato', 'Sindicato:') !!}
                                 {!! Form::text('sindicato',   isset($reporte->comision->cat_sindicato->nombre) ? $reporte->comision->cat_sindicato->nombre : null , array('class' => 'form-control', 'readonly' => true)) !!}
                            </div>
                        </div>
                        <div class="tab-pane" id="presidente">
                            <br>
                                <div class="row">
                                    <div class="col-sm-6 form-group">
                                        {!! Form::label ('presidente', 'Nombre:') !!}
                                        {!! Form::text('presidente', isset($reporte->comision->presidente->nombre_completo) ? $reporte->comision->presidente->nombre_completo : null, array('class' => 'form-control', 'readonly' => true)) !!}
                                    </div>
                                    <div class="col-sm-6 form-group">
                                        {!! Form::label ('cargo', 'Cargo:') !!}
                                        {!! Form::text('cargo',  isset($reporte->comision->presidente->cargo) ? $reporte->comision->presidente->cargo : null, array('class' => 'form-control', 'readonly' => true)) !!}
                                    </div>
                                </div>
                        </div>
                        <div class="tab-pane" id="secretario">
                            <br>
                                <div class="row">
                                    <div class="col-sm-6 form-group">
                                        {!! Form::label ('secretario', 'Nombre:') !!}
                                        {!! Form::text('secretario', isset($reporte->comision->secretario->nombre_completo) ? $reporte->comision->secretario->nombre_completo : null, array('class' => 'form-control', 'readonly' => true)) !!}
                                    </div>
                                    <div class="col-sm-3 form-group">
                                        <?php
                                            if (!isset($reporte->comision->secretario->sector))
                                                $sector = null;
                                            else
                                                if ($reporte->comision->secretario->sector == 1)
                                                    $sector = 'OFICIAL';
                                                else if ($reporte->comision->secretario->sector = 2)
                                                    $sector = 'SINDICAL';
                                        ?>
                                        {!! Form::label ('sector', 'Sector:') !!}
                                        {!! Form::text('sector', $sector , array('class' => 'form-control', 'readonly' => true)) !!}
                                    </div>
                                    <div class="col-sm-3 form-group">
                                        {!! Form::label ('rfc', 'RFC:') !!}
                                        {!! Form::text('rfc', isset($reporte->comision->secretario->rfc) ? $reporte->comision->secretario->rfc : null, array('class' => 'form-control', 'readonly' => true)) !!}
                                    </div>
                                </div>
                        </div>
                        <div class="tab-pane" id="vocales">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>
                                            Nombre
                                        </th>
                                        <th>
                                            Cargo
                                        </th>
                                        <th>
                                            Sector
                                        </th>
                                        <th>
                                            Tipo de representación
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody id="myTable">
                                        @forelse($reporte->comision->vocales as $vocal)
                                            <tr>
                                                <td>{{$vocal->nombre_completo}}</td>
                                                <td>{{$vocal->cargo}}</td>
                                                <td>{{$vocal->nombreSector}}</td>
                                                <td>{{$vocal->nombreTipo}}</td>
                                            </tr>
                                        @empty
                                            <tr>
                                                <td colspan="4"><p>No contiene vocales</p></td>
                                            </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="tab-pane" id="documentacion">
                            <br>
                                <div class="row">
                                    <div class="col-sm-3 control-label" style="text-align: left!important">
                                        {!! Form::label ('oficio_oficial', 'Oficio designación oficial:') !!}
                                    </div>
                                    <div class="col-sm-3">
                                        {!! Form::text('oficio_oficial', isset($reporte->comision->num_oficio_oficial) ? $reporte->comision->num_oficio_oficial : null , array('class' => 'form-control', 'readonly' => true)) !!}
                                    </div>
                                    <div class="col-sm-3 control-label" style="text-align: left!important">
                                        {!! Form::label ('fecha_oficio_oficial', 'Fecha:') !!}
                                    </div>
                                    <div class="col-sm-3">
                                        {!! Form::text('fecha_oficio_oficial', isset($reporte->comision->fecha_oficio_oficial) ? $reporte->comision->fecha_oficio_oficial : null, array('class' => 'form-control', 'readonly' => true)) !!}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-3 control-label" style="text-align: left!important">
                                        {!! Form::label ('oficio_sindical', 'Oficio designación sindical:') !!}
                                    </div>
                                    <div class="col-sm-3">
                                        {!! Form::text('oficio_sindical', isset($reporte->comision->num_oficio_sindical) ? $reporte->comision->num_oficio_sindical : null, array('class' => 'form-control', 'readonly' => true)) !!}
                                    </div>
                                    <div class="col-sm-3 control-label" style="text-align: left!important">
                                        {!! Form::label ('fecha_oficio_sindical', 'Fecha:') !!}
                                    </div>
                                    <div class="col-sm-3">
                                        {!! Form::text('fecha_oficio_sindical', isset($reporte->comision->fecha_oficio_sindical) ? $reporte->comision->fecha_oficio_sindical : null, array('class' => 'form-control', 'readonly' => true)) !!}
                                    </div>
                                </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>